# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetgo < Formula
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j178/leetgo/releases/download/v0.1.3/leetgo_Darwin_x86_64.tar.gz"
      sha256 "3dc33cf98d53606b37cdd2641c462f3034a46117c42f59d0dbf8cf7bc3554c72"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j178/leetgo/releases/download/v0.1.3/leetgo_Darwin_arm64.tar.gz"
      sha256 "37345d726ad0d0d5cdde863d95eb73f78e4827a0dd01c7b57c40f6b293d06015"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j178/leetgo/releases/download/v0.1.3/leetgo_Linux_arm64.tar.gz"
      sha256 "7d832178eb2d3fc7d4335e79b4907574f337b4bdc30ff091a2ad7c2d3d9868bc"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/j178/leetgo/releases/download/v0.1.3/leetgo_Linux_x86_64.tar.gz"
      sha256 "b37581489b2143a437fc85c86f5c6e009850bd0706c5655140064d6159059f9d"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
  end
end
