# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetgo < Formula
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"
  version "1.4.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/j178/leetgo/releases/download/v1.4.9/leetgo_macOS_x86_64.tar.gz"
      sha256 "4970fb6a3206523ecdfb914b93433537e1d5c5e258834fd24e69c90ceb5cb886"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
    on_arm do
      url "https://github.com/j178/leetgo/releases/download/v1.4.9/leetgo_macOS_arm64.tar.gz"
      sha256 "09acc2dc2cb085c1bb56b6e87a960317f60536342da98270e1ee9099e98655e2"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/leetgo/releases/download/v1.4.9/leetgo_linux_x86_64.tar.gz"
        sha256 "17b08f450b887dd2ded963db662c35177b04d52dcb7c92f054ba45a522d22ac1"

        def install
          bin.install "leetgo"
          bash_completion.install "completions/leetgo.bash" => "leetgo"
          zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
          fish_completion.install "completions/leetgo.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/leetgo/releases/download/v1.4.9/leetgo_linux_arm64.tar.gz"
        sha256 "08ff4e3616dc897a9ed0335232324de78f6df87a63ab4871e87d6118ee91f1c1"

        def install
          bin.install "leetgo"
          bash_completion.install "completions/leetgo.bash" => "leetgo"
          zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
          fish_completion.install "completions/leetgo.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/leetgo", "-v"
  end
end
