# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"
  version "1.4.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  zsh_completion "completions/leetgo.zsh"
  fish_completion "completions/leetgo.fish"

  on_macos do
    on_intel do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
      sha256 "4bf70abc9ad0c608373183fa733e10c2e834c43c054fa601df8111af146f0b5d"
    end
    on_arm do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
      sha256 "006ae44d1d30df5bbfa2bba31c9567350461d3ce94545da2a897c7abc34440a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
      sha256 "4d2323a7fd3db066403f486eb87b3a121e042f973f83ec5657d77d3e6237c365"
    end
    on_arm do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
      sha256 "c069d7256d89a7f0496d7310b6f2ff8ec315ea59c83e66aee5d4866dec815057"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required
end
