# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  version "1.5.1"

  on_macos do
    on_arm do
      sha256 "6ef73d7ddbf438d698c28cd922799ae177eb957edad961dd5c31dbe76258fbe0"
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "50bc16aec7bf5227d16ff1e259beb09f49776aae88af7a56dd4fa164d1b8b605"
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3b7553eced10a772da1f5c6bbfc7dd9f2649866012e081ceffe827fe7c763d2c"
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32ea0dc354cba7808d09482a784c10c1af7accc667d70f5b499a426b2d6fb065"
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
    end
  end

  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  fish_completion "completions/leetgo.fish"
  zsh_completion "completions/leetgo.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required
end
