# This file was generated by GoReleaser. DO NOT EDIT.
cask "leetgo" do
  version "1.4.17"

  on_macos do
    on_intel do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_x86_64.tar.gz"
      sha256 "ad18a8ffa447cd6734063e1f1c99b04152c884bfc1942ecc8e37a28441413512"
    end
    on_arm do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_macOS_arm64.tar.gz"
      sha256 "6484df375dac8008320f7bedc2ca9e02ff01a5fe3f65e18ba37bda3cf0563e94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_x86_64.tar.gz"
      sha256 "fe18dc54f2784aded76ef1e04e6917d6d9d8731520bbe232328ba942b5b3c47b"
    end
    on_arm do
      url "https://github.com/j178/leetgo/releases/download/v#{version}/leetgo_linux_arm64.tar.gz"
      sha256 "de77054553b61c1733f9b034e4a976630a3da585e414f93f0ce13ada5dd80ca4"
    end
  end

  name "leetgo"
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leetgo"
  bash_completion "completions/leetgo.bash"
  fish_completion "completions/leetgo.fish"
  zsh_completion "completions/leetgo.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leetgo"]
    end
  end

  # No zap stanza required

end
