# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubS3 < Formula
  desc "Use GitHub as a file server."
  homepage "https://github.com/j178/github-s3"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j178/github-s3/releases/download/v1.0.1/github-s3_Darwin_x86_64.tar.gz"
      sha256 "107fe9f16854368ff4c58f16d3d6261d26762ea817ebb03a58ce23ea9047dcb5"

      def install
        bin.install "github-s3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j178/github-s3/releases/download/v1.0.1/github-s3_Darwin_arm64.tar.gz"
      sha256 "3f4cd1e8e03f4848b4073cd7b0c17140e7bbbb8dae5e9839a60d5b54c3b6ff89"

      def install
        bin.install "github-s3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/github-s3/releases/download/v1.0.1/github-s3_Linux_x86_64.tar.gz"
        sha256 "916dfd479c8909755296a0eca62ace7ad6edb04ed428ba54409b71a1836306af"

        def install
          bin.install "github-s3"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/github-s3/releases/download/v1.0.1/github-s3_Linux_arm64.tar.gz"
        sha256 "0670bb3cab7baa0bd3af025735e6ec11c759a132424f2ac78ede2d33bb3eb370"

        def install
          bin.install "github-s3"
        end
      end
    end
  end
end
