# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetgo < Formula
  desc "leetgo is a command line tool for leetcode.com. It can help you to login, submit, test, and view your submissions."
  homepage "https://github.com/j178/leetgo"
  version "1.4.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j178/leetgo/releases/download/v1.4.12/leetgo_macOS_x86_64.tar.gz"
      sha256 "c53b1d2fa90f31eeaf4eda04d3df7686898a31fc368f069a97c70e81d2420204"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j178/leetgo/releases/download/v1.4.12/leetgo_macOS_arm64.tar.gz"
      sha256 "fcd1f239bc94809474ba6659f7469dd3a62af250c64785a8b9972696407c2a06"

      def install
        bin.install "leetgo"
        bash_completion.install "completions/leetgo.bash" => "leetgo"
        zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
        fish_completion.install "completions/leetgo.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/leetgo/releases/download/v1.4.12/leetgo_linux_x86_64.tar.gz"
        sha256 "3bd0362570041535b7662993d8693509623606544c7ec309895270a15e37b674"

        def install
          bin.install "leetgo"
          bash_completion.install "completions/leetgo.bash" => "leetgo"
          zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
          fish_completion.install "completions/leetgo.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/j178/leetgo/releases/download/v1.4.12/leetgo_linux_arm64.tar.gz"
        sha256 "7d4431b3853a7e1d75c5d09f6e1a940392d0688afd3512d5d183099654d204ae"

        def install
          bin.install "leetgo"
          bash_completion.install "completions/leetgo.bash" => "leetgo"
          zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
          fish_completion.install "completions/leetgo.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/leetgo", "-v"
  end
end
